apiVersion: v1
kind: Service
metadata:
  name: iperf
  labels:
    name: iperf
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 5001
    targetPort: 5001
    protocol: TCP
  type: NodePort
  selector:
    app: iperf
status:
  loadBalancer: {}
