apiVersion: v1
kind: ReplicationController
metadata:
  name: iperf
  labels:
    app: iperf
spec:
  replicas: 2
  selector:
    app: iperf
  template:
    metadata:
      labels:
        app: iperf
        io.contiv.net-group: dev-web-group2
    spec:
      containers:
      - name: iperf
        image: mlabbe/iperf3
        ports:
          - containerPort: 5201
            hostPort: 5201  
