apiVersion: v1
kind: ReplicationController
metadata:
  name: iperf
  labels:
    app: iperf
spec:
  replicas: 1
  selector:
    app: iperf
  template:
    metadata:
      labels:
        app: iperf
        io.contiv.net-group: dev-web-group2
    spec:
      containers:
      - name: iperf
        image: mlabbe/iperf
        ports:
          - containerPort: 5001
            hostPort: 5001  
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
