apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome 
  labels:
    app: selenium-node-chrome
spec:
  replicas: 1
  selector:
    app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
        io.contiv.network: contiv-net
        io.contiv.net-group: dev-web-group4
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/standalone-chrome-debug:2.53.1
        ports:
          - containerPort: 5900 
            hostPort: 5900
        env:
          - name: HUB_PORT_4444_TCP_ADDR 
            value: "127.0.0.1"
          - name: HUB_PORT_4444_TCP_PORT 
            value: "5900"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
