apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
  labels:
    name: selenium-node-chrome
  namespace: default
spec:
  ports:
  - nodePort: 31000
    port: 5900 
    targetPort: 5900
    protocol: TCP
  type: NodePort
  selector:
    app: selenium-node-chrome
status:
  loadBalancer: {}
